# Generated by Django 2.2.4 on 2020-11-04 13:42

import ckeditor.fields
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', ckeditor.fields.RichTextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('objectives', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'AboutUs',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='BankInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150)),
                ('branch', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=250)),
                ('account_name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'BankInformations',
            },
        ),
        migrations.CreateModel(
            name='Carasoul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/%Y/%m/%d/')),
                ('title', models.CharField(max_length=250)),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Carasoul',
            },
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/%Y/%m/%d/')),
                ('title', models.CharField(max_length=150)),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Causes',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='pics/%Y/%m/%d/')),
                ('title', models.CharField(max_length=250)),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phonenumber', models.IntegerField()),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'ContactMessages',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.FloatField(max_length=200)),
                ('transcition_id', models.IntegerField()),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Donations',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/%Y/%m/%d/')),
                ('name', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.CharField(max_length=150, verbose_name='Donors job ?')),
            ],
            options={
                'verbose_name_plural': 'Donors',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Gallaries',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/%Y/%m/%d/')),
                ('name', models.CharField(max_length=150)),
                ('post', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='pics/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Programs',
            },
        ),
    ]
