# Generated by Django 2.2.4 on 2020-11-06 02:17

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201106_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='link',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
