# Generated by Django 2.2.4 on 2020-11-06 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201106_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
