# Generated by Django 2.2.4 on 2020-11-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cause_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'GalleryTitles',
            },
        ),
    ]
