# Generated by Django 2.2.4 on 2020-11-06 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gallerytitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='slug',
        ),
        migrations.AddField(
            model_name='gallery',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.GalleryTitle'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics/%Y/%m/%d/'),
        ),
    ]
