# Generated by Django 2.2.4 on 2020-11-07 01:14

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201106_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='link',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
