# Generated by Django 2.2.4 on 2020-11-07 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201107_0702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='video',
            new_name='link',
        ),
    ]
