# Generated by Django 2.2.4 on 2020-11-07 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201107_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='link',
            new_name='video',
        ),
    ]
