# Generated by Django 2.2.4 on 2020-11-07 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201107_0726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='Item',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
    ]
