# Generated by Django 2.2.4 on 2020-11-07 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201107_0732'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Activity',
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
